### PR TITLE
Rails 4 .1

### PR DESCRIPTION
**Pull request by isaacfreeman**
Here's an update for Rails 4.1.

### CODE REVIEW

**Comment by jokklan** [comment]
Looks awesome! This also seems to add support for Refinerycms 2.1 right :)?

**Comment by isaacfreeman** [comment]
Yes. It's also working for me here on RefineryCMS 3.0.0.dev.

**Comment by isaacfreeman** [comment]
I missed permitting the nested parameters for menu links. Updated.

**Comment by bricesanchez** [comment]
Any update?

**Comment by isaacfreeman** [comment]
Closing as too much time has passed for this to still be relevant.

**Pull request closed without merging**
